env:
  LANG: C
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_CLONE_SUBMODULES: false
  DEFAULT_CONFIG_OPTS: --enable-compatibility-mode --enable-debug --without-libstatgrab --disable-dependency-tracking

###
# Misc non-standard build environment & options on most recent released debian
# version.
# Some are expected to fail, others should always pass
non_standard_toolchains_task:
  container:
    image: collectd/ci:debian12

  matrix:
    # build using clang with default build flags, should always pass
    - env:
        LABEL: clang
      allow_failures: true # TODO: fix this platform
      skip_notifications: true
      git_submodule_script:
        - git submodule init -- opentelemetry-proto
        - git submodule update -- opentelemetry-proto
      configure_script:
        - ./build.sh
        - clang --version
        - >
          ./configure CC=clang CXX=clang++
          $DEFAULT_CONFIG_OPTS
          CFLAGS="$(dpkg-buildflags --get CFLAGS) -gdwarf-4"
          CPPLAGS="$(dpkg-buildflags --get CPPFLAGS)"
          LDFLAGS="$(dpkg-buildflags --get LDFLAGS)"
      build_script:
        - make -j$(nproc) -sk
      tests_script:
        - VALGRIND_OPTS="--errors-for-leak-kinds=definite" make -j$(nproc) -sk check || (cat ./test-suite.log && false)
      always:
        make_check_artifacts:
          path: "**/*.log"

    # build using clang with a collection of strict build flags, will most
    # probably always fail
    - env:
        LABEL: clang strict
      allow_failures: true
      skip_notifications: true
      git_submodule_script:
        - git submodule init -- opentelemetry-proto
        - git submodule update -- opentelemetry-proto
      configure_script:
        - ./build.sh
        - clang --version
        - >
          ./configure CC=clang CXX=clang++
          $DEFAULT_CONFIG_OPTS
          CFLAGS='-gdwarf-4 -Wall
          -Wno-error
          -Wextra
          -Wformat=2
          -Wformat-security
          -Wformat-nonliteral
          -Wmissing-include-dirs
          -Wold-style-definition
          -Wpointer-arith
          -Winit-self
          -Wmissing-prototypes
          -Wimplicit-function-declaration
          -Wmissing-declarations
          -Wstrict-prototypes
          -Wmissing-noreturn
          -Wshadow
          -Wendif-labels
          -Wwrite-strings
          -Wno-unused-parameter
          -Wno-missing-field-initializers
          -Wdate-time
          -Wnested-externs
          -Wno-typedef-redefinition
          -Wno-gnu-variable-sized-type-not-at-end'
      build_script:
        - make -j$(nproc) -sk
      tests_script:
        - VALGRIND_OPTS="--errors-for-leak-kinds=definite" make -j$(nproc) -sk check || (cat ./test-suite.log && false)
      always:
        make_check_artifacts:
          path: "**/*.log"

###
# Build using a range of compilers, available in debian/unstable. NB: might
# fail because of changes to the distro, not the compiler used.
#
bleeding_edge_compilers_task:
  container:
    image: collectd/ci:debian_unstable
  only_if: $CIRRUS_BRANCH == 'main'
  allow_failures: true
  skip_notifications: true
  env:
    matrix:
      CC: gcc-10
      CC: clang
      CC: clang-18
      CC: clang-17
  git_submodule_script:
    - git submodule init -- opentelemetry-proto
    - git submodule update -- opentelemetry-proto
  configure_script:
    - ./build.sh
    - $CC --version
    - >
      ./configure CC=$CC
      $DEFAULT_CONFIG_OPTS
      CFLAGS="$(dpkg-buildflags --get CFLAGS)"
      CPPLAGS="$(dpkg-buildflags --get CPPFLAGS)"
      LDFLAGS="$(dpkg-buildflags --get LDFLAGS)"
  build_script:
    - make -j$(nproc) -sk
  tests_script:
    - VALGRIND_OPTS="--errors-for-leak-kinds=definite" make -j$(nproc) -sk check || (cat ./test-suite.log && false)
  always:
    make_check_artifacts:
      path: "**/*.log"

freebsd_task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-2
  allow_failures: false
  pkg_install_script:
    - >
      pkg install --yes
      git
      autotools
      bison
      flex
      pkgconf
  git_submodule_script:
    - git submodule init -- opentelemetry-proto
    - git submodule update -- opentelemetry-proto
  configure_script:
    - ./build.sh
    - ./configure --disable-perl
  build_script:
    - make -j$(nproc) -sk
  tests_script:
    - VALGRIND_OPTS="--errors-for-leak-kinds=definite" make -j$(nproc) -sk check || (cat ./test-suite.log && false)
  always:
    make_check_artifacts:
      path: "**/*.log"

macos_task:
  macos_instance:
    matrix:
      - image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  allow_failures: false
  git_submodule_script:
    - git submodule init -- opentelemetry-proto
    - git submodule update -- opentelemetry-proto
  brew_install_script:
    - >
      brew install
      autoconf automake
      libtool
      bison
      flex
      pkg-config
  configure_script:
    - ./build.sh
    - ./configure ${DEFAULT_CONFIG_OPTS}
  build_script:
    - make -j "${CIRRUS_CPU}" -sk
  tests_script:
    - make -j "${CIRRUS_CPU}" -sk check || (cat ./test-suite.log && false)
  always:
    make_check_artifacts:
      path: "**/*.log"
