name: Check the Distribution

on:
  push:
    branches: [ collectd-6.0 ]
  pull_request:
    branches: [ collectd-6.0 ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  make_distcheck:
    runs-on: ubuntu-latest
    container: collectd/ci:debian12
    env:
      # this env var picked up by valgrind during make check phase
      VALGRIND_OPTS: "--errors-for-leak-kinds=definite"
    steps:
    - uses: actions/checkout@v4
    - run: |
        git config --global --add safe.directory "$(pwd)"
        git submodule init -- opentelemetry-proto
        git submodule update -- opentelemetry-proto
    - name: Install bzip2
      run: apt install -y bzip2
    - name: Print available packages
      run: pkg-config --list-all | sort
    - name: Generate configure script
      run: ./build.sh
    - name: Run configure script
      run: ./configure
    - name: Run make distcheck
      run: make $MAKEFLAG distcheck
